#175636834 Set up unit testing and add tests for users APIs
atlp-rwanda/tech-strikers-bn-backend pull request #12
Opened 2020-11-13 20:22 UTC by hervebu

#### What does this PR do?
This PR sets up packages for testing and tests users APIs
#### Description of Task to be completed?
 Adds `chai` , `chai-http`, `mocha`, 
 and `nyc`  devdependencies for testing.
Adds  tests for  the  `GET /api/user/:id`
Adds  tests for  the  `POST /api/users` 
Adds  tests for  the  `PUT  /api/user/:id`
Fixes bugs in `src/routes/api/users.js` identified by the tests. 
#### How should this be manually tested?
In the terminal run:
- `git clone https://git.github.com/atlp-rwanda/tech-strikers-bn-backend`
- `cd tech-strikers-bn-backend`
- `npm install`  to install packages used
- `npm run coverage`  to run tests and display coverage results in a table.
#### Any background context you want to provide?
Some codes were changed as they were identified as bugs by the tests.
The test coverage is not at a good coverage percentage
#### What are the relevant pivotal tracker stories?
[#175636834](https://www.pivotaltracker.com/story/show/175636834)
#### Screenshots (if appropriate)
<img width="948" alt="test1" src="https://user-images.githubusercontent.com/48241489/99117284-1dfd6a00-25fe-11eb-9039-946e2e617788.PNG">
<img width="947" alt="test2" src="https://user-images.githubusercontent.com/48241489/99117279-1c33a680-25fe-11eb-9080-ab521c3807c5.PNG">
#### Questions:

2020-11-14 15:19 UTC, BiGelio commented
For me it's ok but try to check for those missing semicolons.

2020-11-15 13:50 UTC, MChristian00 approved these changes
Looks GREAT!

2020-11-15 14:53 UTC, BiGelio commented
It's ok.

2020-11-15 15:29 UTC, BiGelio approved these changes

2020-11-16 16:46 UTC, BiGelio commented
You have to do rebase again.

2020-11-17 08:57 UTC, geraudirad requested changes
Kindly fix hound CI errors.

2020-11-17 08:57 UTC, geraudirad commented on src/routes/api/users.js
>                  return res.sendStatus(401);
I think the status code should be 404 because we are testing for not found.
401 is unauthorized.

2020-11-17 08:57 UTC, geraudirad commented on src/routes/api/users.js
>                  return res.sendStatus(401);
Same here. It should be 404

2020-11-20 14:57 UTC, MChristian00 requested changes
You still have many commits. Please look into that.

2020-11-22 06:30 UTC, hervebu commented
> You still have many commits. Please look into that.

The commits have been merged into one as of now.

2020-11-23 11:19 UTC, Duncanwar commented
@hervebu Solve the conflicts and make sure Travis is passing

2020-11-24 12:54 UTC, hervebu commented
> @hervebu Solve the conflicts and make sure Travis is passing

Conflicts solved and Travis is now passing.

2020-11-24 17:37 UTC, geraudirad approved these changes

2020-11-24 17:38 UTC, geraudirad approved these changes

2020-11-25 09:31 UTC, merged