#175636833 Integrate Travis with read me badge
atlp-rwanda/tech-strikers-bn-backend pull request #14
Opened 2020-11-16 04:22 UTC by roclena

**What does this PR do?**
Add Travis Badge on readMe
 **Description of Task to be completed?**
clone using: git clone https://github.com/atlp-rwanda/tech-strikers-bn-backend
create an account on Travis using GitHub and login
Authorize Travis by activated Repository: tech-strikers-bn-backend
Click the status image in the top right to open a dialog box containing common templates for the status image URL in the markdown
Select the branch and template in the dialog box
Copy the text and paste it into your README
**How should this be manually tested?**
Once open Branch ch-integrate-travis-#175636833 badge appear in unknow status
 **Any background context you want to provide?**
no
**What are the relevant pivotal tracker stories?**
[#175636833](https://www.pivotaltracker.com/n/projects/2475704)
 **Screenshots (if appropriate)**
![image](https://user-images.githubusercontent.com/70943045/99212584-12fc3280-27d4-11eb-84c6-44049c40f88f.png)

**Questions:**

2020-11-16 11:42 UTC, kipropbrian commented
Hey Roger

You need to rebase this PR.
You also need to update the description. Check how others are writing their description
You also need to get 2 reviews from your teammates/

2020-11-16 15:59 UTC, Duncanwar reviewed
Rebase Develop

2020-11-16 16:00 UTC, Duncanwar commented
Resolve conflicts and use back ticks for command in PR

2020-11-16 16:10 UTC, MChristian00 requested changes
Great work so far. Can you please work on the following:
- Rebase. New changes have been merged to Develop and you need to rebase for the conflicts to be resolved.
- Your commit contains two contributors while it should only be showing you. Please work on it.
- As the other reviewers noted, please work on your PR Description.

Good Luck !!

2020-11-16 16:44 UTC, BiGelio commented
Good job Roger but  try to make your description more descriptive, You can just remove somethings like this **node_js:
- 12.18.4
- node**
Instead of doing like this **_clone using: git clone https://github.com/atlp-rwanda/tech-strikers-bn-backend.git_** you can do it in this way `run git clone https://github.com/atlp-rwanda/tech-strikers-bn-backend.git`.

Use backticks

2020-11-16 16:44 UTC, BiGelio commented
Remember to do rebasing also.

2020-11-17 14:49 UTC, geraudirad approved these changes

2020-11-17 19:27 UTC, Duncanwar approved these changes
Now it looks ok

2020-11-18 06:49 UTC, BiGelio commented
Good job @reclina . It looks good.

2020-11-18 06:50 UTC, BiGelio approved these changes

2020-11-19 12:14 UTC, kipropbrian commented on 
> +#
Delete this file, its not necessary

2020-11-20 11:07 UTC, merged