#17563684 Login User and Generate a Token When Password is Excluded
atlp-rwanda/tech-strikers-bn-backend pull request #27
Opened 2020-11-30 20:17 UTC by Thiernope

#### What does this PR do?
Login user to the application, and generate a token containing information with password excluded
#### Description of Task to be completed?

-  check the user existence in the database via the registered email address
-  end the process by sending error if the user is not in the database
-  validate required credentials 
-  login the user and generate the token containing information with password excluded in the token
- write tests to test login functionality

#### How should this be manually tested?

- run `git clone https://github.com/atlp-rwanda/tech-strikers-bn-backend.git`
- run `cd tech-strikers-bn-backend`
- run `git checkout ft-userAuthentication-#17563684`
- run `npm install`
- create  your .env file from .env.example file and add variable ACCESS_TOKEN_SECRET in that file with your random value
- add database username, password and database name in your .env file
- run `sequelize db:migrate`
- run `sequelize db:seed:all` in order to have the seeds and apply login on postman
- run `npm run dev`
- use postiman with `localhost:3000/api/auth/siginIn` to login the existing user in the migrated database by using the following credentials: 
- use `{   
    "email": "evalop@b@gmail.com",
     "password": "M03000jdh"
}`

#### Any background context you want to provide?
The PR tests are not yet passing. Still working on them
#### What are the relevant pivotal tracker stories?
[#17563684](https://www.pivotaltracker.com/n/projects/2475704/stories/175636843)
#### Screenshots (if appropriate)
<img width="1129" alt="login test with postman" src="https://user-images.githubusercontent.com/56275083/100656123-e6f4bb80-3354-11eb-8ba3-1cc97dd05d89.png">

2020-12-01 12:51 UTC, hervebu requested changes
Great work so far teammate, though it's better you add some small changes as requested. And if you've added some functionalities that are someone else's task e.g. validation, they should not be merged from your PR. Only make sure your functionality will be compatible with the replacement of that functionality.

2020-12-01 12:51 UTC, hervebu commented on src/controllers/authController.js
> +        console.log(userInfo);
I think you forgot to remove this console.log(userInfo) because it is like leaking user data.

2020-12-01 12:51 UTC, hervebu commented on src/controllers/authController.js
> +
Remove these unnecessary lines from line 30-33

2020-12-01 12:51 UTC, hervebu commented on src/routes/api/users.js
>  export default router;
Line 6 seems to be a duplicate of line 25. It's better you remove the nonfunctioning one.

2020-12-01 12:51 UTC, hervebu commented on src/routes/api/users.js
> +router.post("/auth/siginIn",validUser,login);
Wouldn't it be better if the login API had the same format as other user-related APIs i.e adding `/user/` in the login API

2020-12-01 19:17 UTC, tytyne reviewed
It looks good to me! but It would be better if you change fullname column  to name.

2020-12-02 07:24 UTC, Thiernope commented
> It looks good to me! but It would be better if you change fullname column to name.

I have put fullname column instead of name column after reviewing what Duncan (who is doing signUp user ) has done in his PR. I think I need to my task of login depends on the user info that is already registered. We can discuss with Duncan then. Thanks

2020-12-02 08:19 UTC, hervebu approved these changes

2020-12-02 11:00 UTC, Duncanwar commented on package.json
> +    "test": "nyc --reporter=text mocha --require @babel/register --experimental-json-modules --timeout 10000 --exit || true",
remove || true

2020-12-02 11:00 UTC, Duncanwar commented on src/controllers/authController.js
> +export default login;
Make this controller a class

2020-12-02 11:00 UTC, Duncanwar commented on src/utils/jwtHelper.js
> +
add new line

2020-12-02 11:00 UTC, Duncanwar commented on src/utils/index.js
> +export const comparePassword = (password, hash) => bcryptjs.compareSync(password, hash);
add new line

2020-12-03 07:18 UTC, Duncanwar reviewed
Do those, I will approve it

2020-12-03 07:18 UTC, Duncanwar commented on package.json
>      "dev": "nodemon --exec babel-node --experimental-json-modules src/index.js",
remove --experimental  because of @babel/register

2020-12-03 07:18 UTC, Duncanwar commented on src/controllers/authController.js
> +class User{
```suggestion
export default class UserController{
```

2020-12-03 07:18 UTC, Duncanwar commented on src/controllers/authController.js
> +class User{
so you remove the export default at the end of line

2020-12-03 07:18 UTC, Duncanwar commented on src/controllers/authController.js
> +  async login(req, res, next){
```suggestion
 static async login(req, res, next){
```
so that the method can be accessible in other files

2020-12-03 07:18 UTC, Duncanwar commented on src/controllers/authController.js
> +export default user;
remove line 30 & 31

2020-12-03 07:18 UTC, Duncanwar commented on src/utils/index.js
> +export const comparePassword = (password, hash) => bcryptjs.compareSync(password, hash);
you can try to forge it

2020-12-03 08:00 UTC, Duncanwar reviewed
Your PR looks good. Implement those minor changes.

2020-12-03 08:00 UTC, Duncanwar commented on src/controllers/authController.js
> +const { comparePassword } = require("../utils");
```suggestion
import { comparePassword } from "../utils/index.js";
```
require is es5. We must use es6 as much as possible

2020-12-03 08:00 UTC, Duncanwar commented on src/controllers/authController.js
> +        return res.status(400).send({error: "Email not found"});
```suggestion
        return res.status(400).json({error: "Email not found"}); 
```
send means turns in value into tex/html while json treats it as an object

2020-12-03 08:00 UTC, Duncanwar commented on src/controllers/authController.js
> +        return res.status(200).send({ message: "successfully logged in", token})
same here use json

2020-12-03 08:00 UTC, Duncanwar commented on src/controllers/authController.js
> +        return res.status(400).send({error: "Wrong password"});
same here use json instead of send

2020-12-03 08:35 UTC, Duncanwar commented on src/index.js
>  // CONNECTING APP TO POSTGRESS
remove line 30 to 37. We no longer need it.

2020-12-03 08:35 UTC, Duncanwar commented on src/index.js
>  // CONNECTING APP TO POSTGRESS
They are braking deepcode analyzer

2020-12-11 08:24 UTC, Duncanwar approved these changes
Well done

2020-12-11 08:51 UTC, tytyne approved these changes
it seems cool to me. but can you please change the name of the controller!?cause social login has the  same name!

2020-12-24 10:40 UTC, merged