#175636847 Add routes for getting and updating profile information
atlp-rwanda/tech-strikers-bn-backend pull request #29
Opened 2020-12-01 20:21 UTC by hervebu

#### What does this PR do?
Adds functionality for getting user information by id.
Adds functionality for updating user information.
#### Description of Task to be completed?
- When the user is logged in, he/she can get his/her profile
information by id decoded from user token.
- The logged-in user also is able to update his profile information.
#### How should this be manually tested?
- clone the repo by `git clone https://github.com/atlp-rwanda/tech-strikers-bn-backend.git`
- run `cd tech-strikers-bn-backend`
- run `git checkout ft-profile-page-settings-175636847`
- run `npm install`
- run `npm run dev`
- use postman to test `GET  http://localhost:3000/api/user/1`
-use postman to test  `PUT http://localhost:3000/api/user/1` 
#### Any background context you want to provide?
Not yet completed the functionality and no tests available for now.
#### What are the relevant pivotal tracker stories?
[#175636847](https://www.pivotaltracker.com/story/show/175636847)
#### Screenshots (if appropriate)
#### Questions:

2020-12-01 20:29 UTC, tytyne requested changes
I thought changing profile, we had to add picture  and other information related to the user!

2020-12-02 10:32 UTC, Duncanwar reviewed
Implement those feedback

2020-12-02 10:32 UTC, Duncanwar commented on src/controllers/user.controller.js
> +export default { getUserInfo, upDateUser };
Can you transform your functions into a class?
For readability and solid principles

2020-12-02 10:32 UTC, Duncanwar commented on src/services/user.service.js
> +export default { retrieveUser, upDateUserInfo };
We can use a class

2020-12-02 10:32 UTC, Duncanwar commented on src/routes/api/users.js
>  export default router;
You don't have to remove the above lines.

2020-12-06 12:15 UTC, hervebu commented
> I thought changing profile, we had to add a picture and other information related to the user!

Now user information and a profile picture included can be added.

2020-12-13 17:02 UTC, tytyne approved these changes

2020-12-13 20:27 UTC, Duncanwar approved these changes

2020-12-24 16:53 UTC, merged