#175636852 Add User Role-Setting for Super Administrator to Assign Roles to Users Using Their Emails
atlp-rwanda/tech-strikers-bn-backend pull request #35
Opened 2020-12-14 06:36 UTC by Thiernope

#### What does this PR do?
Add User Role-Setting for Super Administrator to Assign Roles to Users Using Their Emails
#### Description of Task to be completed?

- create userRole models 
- add column of roles in the User model
- create superAdmin role
- Add functionalities to create, read, update and delete users roles using their emails

#### How should this be manually tested?

- run `git clone https://github.com/atlp-rwanda/tech-strikers-bn-backend.git`
- run `cd directory tech-strikers-bn-backend`
- run `git checkout ft-notify-on-edit-175636861`

#### Any background context you want to provide?
no info so far
#### What are the relevant pivotal tracker stories?
[#175636852](https://www.pivotaltracker.com/n/projects/2475704/stories/175636852)
#### Screenshots (if appropriate)
No so far
#### Questions:
No so far

2020-12-15 19:29 UTC, Duncanwar reviewed
I am no seeing any file changed

2020-12-21 11:13 UTC, hervebu requested changes
Left some comments and check for similar issues that reviewers may not have seen.

2020-12-21 11:13 UTC, hervebu commented on src/database/models/user.js
> +      roleId: DataTypes.STRING,
roleId should be an integer

2020-12-21 11:13 UTC, hervebu commented on src/database/migrations/20201118122004-create-user.js
>          defaultValue: "user",
roleId type should be integer and the default value should no longer be 'user'

2020-12-21 11:13 UTC, hervebu commented on src/database/superAdminRole.js
> +}
Console logging not advisable for production

2020-12-21 11:13 UTC, hervebu commented on src/database/superAdmin.js
> +    console.log("super admin has been created")
Console logging not advisable for production

2020-12-23 10:07 UTC, closed without merging