#175636853  Approve or Reject Trip Request
atlp-rwanda/tech-strikers-bn-backend pull request #47
Opened 2021-01-22 19:56 UTC by roclena

**What does this PR do?**
This PR adds the route for Approve  or reject for pending Trip Request by Manager
**Description of Task to be completed?**
It adds functionality for Manager to Approve or Reject the trip request with pending status.
**How should this be manually tested?**
.` clone the repo by git clone https://github.com/atlp-rwanda/tech-strikers-bn-backend.git`
. `run cd tech-strikers-bn-backend`
. `run git checkout ft-Approve-reject-trip request-175636853`
. `run npm install`
Any background context you want to provide?
The created route has token verification i.e adding a manager  token in the header
**What are the relevant pivotal tracker stories?**
[#175636853](https://www.pivotaltracker.com/story/show/175636853)
 Screenshots (if appropriate)
![image](https://user-images.githubusercontent.com/70943045/105537620-dfb9b080-5cfa-11eb-9e8e-1b4dece0a03d.png)
![image](https://user-images.githubusercontent.com/70943045/105537936-5e165280-5cfb-11eb-8794-9666635b9029.png)
![image](https://user-images.githubusercontent.com/70943045/105537960-679fba80-5cfb-11eb-81c6-c08f5ac5b824.png)
![image](https://user-images.githubusercontent.com/70943045/105538043-8736e300-5cfb-11eb-947b-41b65653bf5c.png)

**Questions:**

2021-02-01 10:12 UTC, hervebu requested changes

2021-02-01 10:12 UTC, hervebu commented on src/database/migrations/20210122204014-create-trip.js
> -      },
Please don't remove these lines of code!

2021-02-06 06:18 UTC, Thiernope approved these changes

2021-02-16 08:56 UTC, hervebu approved these changes

2021-02-16 14:52 UTC, merged