Ch setup sequelize 175636830
atlp-rwanda/tech-strikers-bn-backend pull request #7
Opened 2020-11-11 19:56 UTC by tytyne

#### What does this PR do?
- The PR setup sequelize in the project
#### Description of Task to be completed?
- creating sequelizerc file 
- creating migrations folder
- creating seeders folder
- creating models folder 

#### How should this be manually tested?
- git clone https://github.com/atlp-rwanda/tech-strikers-bn-backend
- git checkout ch-setup-sequelize-175636830
- npm run start 
#### Any background context you want to provide?
no
#### What are the relevant pivotal tracker stories?
#175636830
#### Screenshots (if appropriate)
sequelizerc file
![sequelize](https://user-images.githubusercontent.com/45592250/98858061-a944f700-2468-11eb-8197-d9d55090904f.PNG)

#### Questions:

2020-11-12 08:48 UTC, Duncanwar commented
In How it is manually tested you can ass the sequelize command

2020-11-13 14:42 UTC, kipropbrian requested changes
Please check the comments and rebase with develop again

2020-11-13 14:42 UTC, kipropbrian commented on .gitignore
> +package-lock.json
Remove package.lock from gitignore

2020-11-13 14:42 UTC, kipropbrian commented on package.json
> +    "@babel/preset-env": "^7.12.1",
These are not dev dependencies.

2020-11-17 08:47 UTC, geraudirad requested changes

2020-11-17 08:47 UTC, geraudirad commented on package.json
> +  "description": "[![Reviewed by Hound](https://img.shields.io/badge/Reviewed_by-Hound-8E64B0.svg)](https://houndci.com)",
I think this should be the project description.
Hound badge has to be added in the readme.

2020-11-18 14:50 UTC, closed without merging